CREATE TABLE  KDR_DEITIES
   (	DEITY_CODE VARCHAR2(100) NOT NULL ENABLE,
	DEITY_NAME VARCHAR2(300) NOT NULL ENABLE,
	DEITY_DESC VARCHAR2(4000),
	DEITY_ICON VARCHAR2(300),
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_DEITIES_PK PRIMARY KEY (DEITY_CODE)
  USING INDEX  ENABLE
   )