create table kdr_item_flux (
    item_flux_id number generated BY DEFAULT ON NULL as identity,
    item_id       number,
    flux_date     date default localtimestamp,
    item_new_cost number,
    constraint  kdr_item_flux_pk primary key (item_flux_id)
)
/

ALTER TABLE kdr_item_flux
ADD CONSTRAINT kdr_item_flux_fk
  FOREIGN KEY (item_id)
  REFERENCES kdr_items(item_id)
/