
  CREATE TABLE KDR_PLOT_NOTES
   (	NOTE_ID NUMBER NOT NULL ENABLE,
	NOTE_TEXT CLOB NOT NULL ENABLE,
	NOTE_USER VARCHAR2(300) NOT NULL ENABLE,
	NOTE_ICON VARCHAR2(300),
	NOTE_TEXT_MODIFIERS VARCHAR2(1000),
	NOTE_ICON_MODIFIERS VARCHAR2(1000),
	PLOT_ID NUMBER NOT NULL ENABLE,
	NOTE_TIMESTAMP TIMESTAMP (6) DEFAULT LOCALTIMESTAMP NOT NULL ENABLE,
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_PLOT_NOTES_PK PRIMARY KEY (NOTE_ID) ENABLE,
	 CONSTRAINT KDR_PLOT_NOTES_PLOT_FK FOREIGN KEY (PLOT_ID)
	  REFERENCES KDR_PLOT (PLOT_ID) ON DELETE CASCADE ENABLE
   )
/