CREATE TABLE  KDR_CHAR_RECIPES
   (	CHAR_RECIPE_ID NUMBER,
	RECIPE_ID NUMBER,
	CHAR_ID NUMBER,
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_CHAR_RECIPES_PK PRIMARY KEY (CHAR_RECIPE_ID)
  USING INDEX  ENABLE
   )