CREATE TABLE  KDR_CHAR_ITEMS
   (	CHAR_ID NUMBER,
	ITEM_ID NUMBER,
	CHAR_ITEM_AMOUNT NUMBER DEFAULT 1,
	CHAR_ITEM_ID NUMBER,
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_CHAR_ITEMS_PK PRIMARY KEY (CHAR_ITEM_ID)
  USING INDEX  ENABLE
   )