
  CREATE TABLE KDR_SKILL_LEVELS 
   (	SKILL_LEVEL_ID NUMBER NOT NULL ENABLE,  
	SKILL_ID NUMBER NOT NULL ENABLE,  
	LEVEL_ID NUMBER NOT NULL ENABLE,  
	SKILL_COST NUMBER NOT NULL ENABLE,  
	SKILL_DESC VARCHAR2(4000),  
	SKILL_MANA_GAIN NUMBER,  
	SKILL_DIV_GAIN NUMBER,  
	SKILL_XP_GAIN NUMBER,  
	SKILL_ARCANE_GAIN NUMBER,  
	SKILL_CHAOS_GAIN NUMBER,  
	SKILL_HP_GAIN NUMBER,  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_SKILL_LEVELS_PK PRIMARY KEY (SKILL_LEVEL_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_SKILL_LEVELS_UK1 UNIQUE (SKILL_ID, LEVEL_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_SKILL_LEVELS_FK FOREIGN KEY (SKILL_ID) 
	  REFERENCES KDR_SKILLS (SKILL_ID) ON DELETE CASCADE ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

