create table kdr_months
(
    month_id        number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder nocycle  nokeep  noscale  not null enable,
    month_name      varchar2(300),
    month_seq       number,
    month_amt_weeks number,
    month_week_days number,
    month_days_corr number,
    month_bg_color  varchar2(300)
);