CREATE table KDR_ARTEFACTS (
    ARTEFACT_ID         NUMBER GENERATED ALWAYS AS IDENTITY,
    ARTEFACT_NAME       VARCHAR2(300),
    ARTEFACT_DESC       VARCHAR2(4000),
    ARTEFACT_GUARDIAN   VARCHAR2(4000),
    ARTEFACT_XP         NUMBER default on null 0,
    constraint  KDR_ARTEFACTS_PK primary key (ARTEFACT_ID)
)
/