
  CREATE TABLE KDR_SPELLS 
   (	SPELL_ID NUMBER NOT NULL ENABLE,  
	SPELL_NAME VARCHAR2(300) NOT NULL ENABLE,  
	SPELL_DISTANCE NUMBER NOT NULL ENABLE,  
	SPELL_DURATION NUMBER NOT NULL ENABLE,  
	SPELL_TARGET VARCHAR2(300) NOT NULL ENABLE,  
	SPELL_LEVEL NUMBER(2,0) NOT NULL ENABLE,  
	SPELL_DESC CLOB,  
	SPELL_MANA_COST VARCHAR2(300) NOT NULL ENABLE,  
	SPELL_TYPE_CODE VARCHAR2(30),  
	SPELL_USAGE VARCHAR2(300),  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_SPELLS_PK PRIMARY KEY (SPELL_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_SPELLS_DIST_FK FOREIGN KEY (SPELL_DISTANCE) 
	  REFERENCES KDR_DISTANCES (DISTANCE_ID) ENABLE,  
	 CONSTRAINT KDR_SPELLS_DURA_FK FOREIGN KEY (SPELL_DURATION) 
	  REFERENCES KDR_DURATIONS (DURATION_ID) ENABLE,  
	 CONSTRAINT KDR_SPELLS_TYPE_FK FOREIGN KEY (SPELL_TYPE_CODE) 
	  REFERENCES KDR_SPELL_TYPES (SPELL_TYPE_CODE) ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
 LOB (SPELL_DESC) STORE AS BASICFILE (
   ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

