
  CREATE TABLE KDR_EVENTS 
   (	EVENT_ID NUMBER NOT NULL ENABLE,  
	EVENT_NAME VARCHAR2(100),  
	EVENT_LOCATION VARCHAR2(100),  
	EVENT_TYPE VARCHAR2(100),  
	EVENT_START_DATE DATE,  
	EVENT_END_DATE DATE,  
	EVENT_XP NUMBER(3,0),  
	EVENT_EXP_PLAYER_AMOUNT NUMBER,  
	EVENT_EXP_NPC_AMOUNT NUMBER,  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_EVENTS_PK PRIMARY KEY (EVENT_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_EVENTS_TYPE_CHK CHECK ( EVENT_TYPE in ('BARAVOND','SPECIAL','MA 
IN')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

