CREATE TABLE  KDR_LANGUAGES
   (	LANGUAGE_ID NUMBER NOT NULL ENABLE,
	LANGUAGE_NAME VARCHAR2(300) NOT NULL ENABLE,
	LANGUAGE_TYPE VARCHAR2(10) NOT NULL ENABLE,
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_LANGUAGES_PK PRIMARY KEY (LANGUAGE_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT KDR_LANGUAGE_TYPE_CK CHECK (LANGUAGE_TYPE in ('GENERAL','MAGIC')) ENABLE,
	 CONSTRAINT KDR_LANGUAGES_NAME_UK UNIQUE (LANGUAGE_NAME)
  USING INDEX  ENABLE
   )