
  CREATE TABLE KDR_CHAR_NOTES 
   (	NOTE_ID NUMBER NOT NULL ENABLE,  
	NOTE_TEXT CLOB NOT NULL ENABLE,  
	NOTE_USER VARCHAR2(300) NOT NULL ENABLE,  
	NOTE_ICON VARCHAR2(300),  
	NOTE_TEXT_MODIFIERS VARCHAR2(1000),  
	NOTE_ICON_MODIFIERS VARCHAR2(1000),  
	CHAR_ID NUMBER NOT NULL ENABLE,  
	NOTE_TIMESTAMP TIMESTAMP (6) DEFAULT LOCALTIMESTAMP NOT NULL ENABLE,  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_CHAR_NOTES_PK PRIMARY KEY (NOTE_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_CHAR_NOTES_CHAR_FK FOREIGN KEY (CHAR_ID) 
	  REFERENCES KDR_CHARACTERS (CHAR_ID) ON DELETE CASCADE ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
 LOB (NOTE_TEXT) STORE AS BASICFILE (
   ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

