CREATE TABLE  KDR_CHAR_SKILLS
   (	CHAR_SKILL_ID NUMBER NOT NULL ENABLE,
	CHAR_ID NUMBER NOT NULL ENABLE,
	SKILL_LEVEL_ID NUMBER,
	CHAR_SKILL_REMARK VARCHAR2(1000),
	CHAR_SKILL_ADD_DATE TIMESTAMP (6) DEFAULT localtimestamp,
	CHAR_SKILL_ADD_SOURCE VARCHAR2(100),
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_CHAR_SKILLS_PK PRIMARY KEY (CHAR_SKILL_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT KDR_CHAR_SKILL_UK UNIQUE (CHAR_ID, SKILL_LEVEL_ID)
  USING INDEX  ENABLE
   )