CREATE TABLE  KDR_RECIPES
   (	RECIPE_ID NUMBER,
	RECIPE_NAME VARCHAR2(1000),
	RECIPE_LEVEL NUMBER,
	RECIPE_INSTRUCTIONS VARCHAR2(4000),
	RECIPE_EFFECT VARCHAR2(4000),
	RECIPE_TYPE_ID NUMBER,
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_RECIPES_PK PRIMARY KEY (RECIPE_ID)
  USING INDEX  ENABLE
   )