CREATE TABLE  KDR_RECIPE_TYPES
   (	RECIPE_TYPE_ID NUMBER,
	RECIPE_TYPE_NAME VARCHAR2(300),
	RECIPE_TYPE_DESC VARCHAR2(4000),
	RECIPE_TYPE_ICON VARCHAR2(300),
	RECIPE_TYPE_ICON_ATTR VARCHAR2(1000),
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_RECIPE_TYPES_PK PRIMARY KEY (RECIPE_TYPE_ID)
  USING INDEX  ENABLE
   )