
  CREATE TABLE KDR_LAMMIES 
   (	LAMMY_ID NUMBER NOT NULL ENABLE,  
	PLOT_ID NUMBER,  
	LAMMY_NAME VARCHAR2(1000),  
	LAMMY_EFFECT VARCHAR2(4000),  
	LAMMY_EXP_DATE VARCHAR2(100),  
	LAMMY_CHARGES NUMBER,  
	LAMMY_QUANTITY NUMBER DEFAULT '1',  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_LAMMIES_PK PRIMARY KEY (LAMMY_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_LAMMIES_PLOT_ID_FK FOREIGN KEY (PLOT_ID) 
	  REFERENCES KDR_PLOT (PLOT_ID) ON DELETE CASCADE ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

