CREATE table KDR_ARTEFACT_LEVELS (
    ARTEFACT_LEVEL_ID     NUMBER GENERATED ALWAYS AS IDENTITY,
    ARTEFACT_ID           NUMBER,
    ARTEFACT_LEVEL        NUMBER,
    ARTEFACT_ABILITY      VARCHAR2(300),
    ARTEFACT_ABILITY_DESC VARCHAR2(4000),
    ARTEFACT_LEVEL_XP     NUMBER,
    constraint  KDR_ARTEFACT_LEVELS_PK primary key (ARTEFACT_LEVEL_ID)
)
/

ALTER TABLE KDR_ARTEFACT_LEVELS ADD CONSTRAINT KDR_ARTEFACT_LEVELS_FK
FOREIGN KEY (ARTEFACT_ID)
REFERENCES KDR_ARTEFACTS (ARTEFACT_ID)

/