CREATE table KDR_SKILL_LEVELS (
    SKILL_ID          NUMBER NOT NULL,
    LEVEL_ID          NUMBER NOT NULL,
    SKILL_COST        NUMBER NOT NULL,
    SKILL_DESC        VARCHAR2(4000),
    SKILL_MANA_GAIN   NUMBER,
    SKILL_DIV_GAIN    NUMBER,
    SKILL_XP_GAIN     NUMBER,
    SKILL_ARCANE_GAIN NUMBER,
    SKILL_CHAOS_GAIN  NUMBER
)
/

alter table KDR_SKILL_LEVELS add constraint  KDR_SKILL_LEVELS_PK primary key (SKILL_ID,LEVEL_ID)
/

ALTER TABLE KDR_SKILL_LEVELS ADD CONSTRAINT KDR_SKILL_LEVELS_FK
FOREIGN KEY (SKILL_ID)
REFERENCES KDR_SKILLS (SKILL_ID)
ON DELETE CASCADE