create table KDR_CHAR_TAGS(
    CHAR_TAG_ID   number
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 CACHE 20 )
        not null enable,
    CHAR_ID       number(30, 0),
    TAG_ID        number(30, 0),
    constraint KDR_CHAR_TAGS_PK primary key(CHAR_TAG_ID)
        using index pctfree 10 initrans 2 maxtrans 255 compute statistics tablespace SH1BLUE21
    enable,
    constraint KDR_CHAR_TAGS_UK1 unique(CHAR_ID,TAG_ID)
        using index pctfree 10 initrans 2 maxtrans 255 compute statistics tablespace SH1BLUE21
    enable,
    constraint KDR_CHAR_TAGS_FK2 foreign key(TAG_ID)
        references SH1BLUE21.KDR_TAGS(TAG_ID)
            on delete cascade
    enable,
    constraint KDR_CHAR_TAGS_FK foreign key(CHAR_ID)
        references SH1BLUE21.KDR_CHARACTERS(CHAR_ID)
            on delete cascade
    enable
);