CREATE TABLE  KDR_CHAR_EVENTS
   (	CHAR_EVENT_ID NUMBER NOT NULL ENABLE,
	EVENT_ID NUMBER NOT NULL ENABLE,
	CHAR_ID NUMBER NOT NULL ENABLE,
	CHAR_EVENT_XP_ADJ NUMBER,
	CHAR_EVENT_XP_REMARK VARCHAR2(300),
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_CHAR_EVENTS_PK PRIMARY KEY (CHAR_EVENT_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT KDR_CHAR_EVENTS_UK UNIQUE (EVENT_ID, CHAR_ID)
  USING INDEX  ENABLE
   )