CREATE TABLE  KDR_ITEMS
   (	ITEM_ID NUMBER,
	ITEM_NAME VARCHAR2(300) NOT NULL ENABLE,
	ITEM_DESC VARCHAR2(1000),
	ITEM_COST NUMBER(10,0),
	ITEM_LEVEL NUMBER(2,0),
	ITEM_DIRECT_EFFECT VARCHAR2(4000),
	ITEM_BONUS_EFFECT VARCHAR2(4000),
	ITEM_BAD_EFFECT VARCHAR2(4000),
	ITEM_TYPES_ARRAY VARCHAR2(300),
	COMP_SEARCH_SKILL_ARRAY VARCHAR2(300),
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	RECIPE_ID NUMBER,
	RECIPE_COST NUMBER,
	 CONSTRAINT KDR_ITEMS_PK PRIMARY KEY (ITEM_ID)
  USING INDEX  ENABLE
   )