CREATE TABLE  KDR_RACES
   (	RACE_ID NUMBER NOT NULL ENABLE,
	RACE_NAME VARCHAR2(300) NOT NULL ENABLE,
	RACE_DESC CLOB DEFAULT '%TODO',
	RACE_XP_PEN NUMBER DEFAULT 0,
	RACE_GOLD NUMBER DEFAULT 0,
	RACE_SKILL_CATEGORY NUMBER NOT NULL ENABLE,
	RACE_SKILL_AMOUNT NUMBER DEFAULT 0 NOT NULL ENABLE,
	RACE_TYPE VARCHAR2(5) DEFAULT 'BASIS',
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_RACES_PK PRIMARY KEY (RACE_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT KDR_RACE_SKILL_AMOUNT_POS CHECK ( RACE_SKILL_AMOUNT >= 0) ENABLE,
	 CONSTRAINT KDR_RACE_TYPE_CK CHECK (race_type in(
        'BASIS',
        'SUB'
    )) ENABLE,
	 CONSTRAINT KDR_RACES_NAME_UK UNIQUE (RACE_NAME)
  USING INDEX  ENABLE
   )