create table kdr_days
(
    day_id          number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder nocycle  nokeep  noscale  not null enable,
    day_name        varchar2(300),
    day_seq         number
);