
  CREATE TABLE KDR_PLOT 
   (	PLOT_ID NUMBER NOT NULL ENABLE,  
	EVENT_ID NUMBER,  
	PLOT_TITLE VARCHAR2(300),  
	PLOT_CATEGORY VARCHAR2(300),  
	PLOT_SIZE VARCHAR2(30),  
	PLOT_GROUP_TYPE VARCHAR2(30),  
	PLOT_TIMING VARCHAR2(30),  
	PLOT_PROPPS VARCHAR2(4000),  
	PLOT_LOCATION VARCHAR2(300),  
	PLOT_GOAL VARCHAR2(4000),  
	PLOT_TARGET VARCHAR2(300),  
	PLOT_GAMEMASTER VARCHAR2(300),  
	PLOT_AUTHOR VARCHAR2(300),  
	PLOT_DESCRIPTION CLOB,  
	PLOT_NPCS VARCHAR2(4000),  
	PLOT_SEQ NUMBER DEFAULT 999 NOT NULL ENABLE,  
	PLOT_CHECKED VARCHAR2(1) DEFAULT 'N',  
	PLOT_READY VARCHAR2(1),  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_PLOT_PK PRIMARY KEY (PLOT_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
 LOB (PLOT_DESCRIPTION) STORE AS BASICFILE (
   ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

