create table kdr_weeks
(
    week_id         number generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache 20 noorder nocycle  nokeep  noscale  not null enable,
    week_seq        number
);