
  CREATE TABLE KDR_RECIPE_COMPONENTS 
   (	COMP_ID NUMBER,  
	RECIPE_ID NUMBER,  
	COMP_AMOUNT NUMBER DEFAULT 1 NOT NULL ENABLE,  
	ITEM_ID NUMBER,  
	COMP_LEVEL NUMBER,  
	ITEM_TYPE_ID NUMBER,  
	COMP_COMMENT VARCHAR2(100),  
	COMP_AMOUNT_UPPER NUMBER,  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_RECIPE_COMPONENTS_PK PRIMARY KEY (COMP_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_RECIPE_COMPONENTS_FK2 FOREIGN KEY (ITEM_ID) 
	  REFERENCES KDR_ITEMS (ITEM_ID) ENABLE,  
	 CONSTRAINT KDR_RECIPE_COMPONENTS_FK3 FOREIGN KEY (ITEM_TYPE_ID) 
	  REFERENCES KDR_ITEM_TYPES (ITEM_TYPE_ID) ENABLE,  
	 CONSTRAINT KDR_RECIPE_COMPONENTS_FK FOREIGN KEY (RECIPE_ID) 
	  REFERENCES KDR_RECIPES (RECIPE_ID) ON DELETE CASCADE ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

