CREATE TABLE  KDR_SKILL_CATEGORIES
   (	CATEGORY_ID NUMBER NOT NULL ENABLE,
	CATEGORY_NAME VARCHAR2(200) NOT NULL ENABLE,
	CATEGORY_DESC VARCHAR2(4000),
	CATEGORY_TYPE NUMBER,
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_SKILL_CATEGORIES_PK PRIMARY KEY (CATEGORY_ID)
  USING INDEX  ENABLE
   )