
  CREATE TABLE KDR_RACES 
   (	RACE_ID NUMBER NOT NULL ENABLE,  
	RACE_NAME VARCHAR2(300) NOT NULL ENABLE,  
	RACE_DESC CLOB DEFAULT '%TODO',  
	RACE_XP_PEN NUMBER DEFAULT 0,  
	RACE_GOLD NUMBER DEFAULT 0,  
	RACE_SKILL_CATEGORY NUMBER NOT NULL ENABLE,  
	RACE_SKILL_AMOUNT NUMBER DEFAULT 0 NOT NULL ENABLE,  
	RACE_TYPE VARCHAR2(5) DEFAULT 'BASIS',  
	AUDIT_CREATION_DATE DATE INVISIBLE,  
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_DATE DATE INVISIBLE,  
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,  
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,  
	 CONSTRAINT KDR_RACES_PK PRIMARY KEY (RACE_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_RACE_SKILL_AMOUNT_POS CHECK ( RACE_SKILL_AMOUNT >= 0) ENABLE,  
	 CONSTRAINT KDR_RACE_TYPE_CK CHECK (race_type in( 
        'BASIS',
        'SUB'
    )) ENABLE, 
	 CONSTRAINT KDR_RACES_NAME_UK UNIQUE (RACE_NAME) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE, 
	 CONSTRAINT KDR_RACES_FK FOREIGN KEY (RACE_SKILL_CATEGORY) 
	  REFERENCES KDR_SKILL_CATEGORIES (CATEGORY_ID) ENABLE 
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
 LOB (RACE_DESC) STORE AS BASICFILE (
   ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

