CREATE TABLE  KDR_PLAYERS
   (	PLAYER_ID NUMBER NOT NULL ENABLE,
	PLAYER_NAME VARCHAR2(300) NOT NULL ENABLE,
	PLAYER_USER_NAME VARCHAR2(300),
	PLAYER_PIN VARCHAR2(300),
	AUDIT_CREATION_DATE DATE INVISIBLE,
	AUDIT_CREATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_CREATION_SOURCE VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_DATE DATE INVISIBLE,
	AUDIT_MUTATION_USER VARCHAR2(1000) INVISIBLE,
	AUDIT_MUTATION_SOURCE VARCHAR2(1000) INVISIBLE,
	 CONSTRAINT KDR_PLAYERS_PK PRIMARY KEY (PLAYER_ID)
  USING INDEX  ENABLE,
	 CONSTRAINT KDR_PLAYERS_US_NAME_UK UNIQUE (PLAYER_USER_NAME)
  USING INDEX  ENABLE
   )
/