
  CREATE OR REPLACE FORCE EDITIONABLE VIEW KDR_NPC_PER_PLOT (NPC_ID, NPC_RACE, N
PC_NAME, NPC_PERSONALITY, NPC_SKILLS, NPC_HITPOINTS, NPC_MANA, NPC_ARC_MANA, NPC
_CHAOS_MANA, NPC_DIVINITY, NPC_ITEMS, NPC_DRESSCODE, NPC_DESC, NPC_SHORT_DESC, P
LOT_ID, EVENT_ID, PLOT_TITLE, PLOT_CATEGORY, PLOT_SIZE, PLOT_GROUP_TYPE, PLOT_TI
MING, PLOT_PROPPS, PLOT_LOCATION, PLOT_GOAL, PLOT_TARGET, PLOT_GAMEMASTER, PLOT_
AUTHOR, PLOT_DESCRIPTION, PLOT_NPCS, PLOT_SEQ, PLOT_CHECKED, PLOT_NPC_QUANTITY, 
PLOT_NPC_QUANTITY_UPPER, EVENT_NAME) AS 
  select  n.NPC_ID,n.NPC_RACE,n.NPC_NAME,n.NPC_PERSONALITY,n.NPC_SKILLS,n.NPC_HI
TPOINTS,n.NPC_MANA,n.NPC_ARC_MANA,n.NPC_CHAOS_MANA,n.NPC_DIVINITY,n.NPC_ITEMS,n.
NPC_DRESSCODE,n.NPC_DESC,n.NPC_SHORT_DESC,
        p.PLOT_ID,p.EVENT_ID,p.PLOT_TITLE,p.PLOT_CATEGORY,p.PLOT_SIZE,p.PLOT_GRO
UP_TYPE,p.PLOT_TIMING,p.PLOT_PROPPS,p.PLOT_LOCATION,p.PLOT_GOAL,p.PLOT_TARGET,p.
PLOT_GAMEMASTER,p.PLOT_AUTHOR,p.PLOT_DESCRIPTION,p.PLOT_NPCS,p.PLOT_SEQ,p.PLOT_C
HECKED,
        pn.plot_npc_quantity,
        pn.plot_npc_quantity_upper,
        e.event_name
from    kdr_npcs        n,
        kdr_plot        p,
        kdr_plot_npcs   pn,
        kdr_events      e
where   n.npc_id    = pn.npc_id
and     p.plot_id   = pn.plot_id
and     p.event_id  = e.event_id;

