
  CREATE OR REPLACE FORCE EDITIONABLE VIEW KDR_NPCS_VIEW (NPC_ID, NPC_RACE, NPC_
NAME, NPC_PERSONALITY, NPC_SKILLS, NPC_HITPOINTS, NPC_MANA, NPC_ARC_MANA, NPC_CH
AOS_MANA, NPC_DIVINITY, NPC_ITEMS, NPC_DRESSCODE, NPC_DESC, NPC_SHORT_DESC, NPC_
PLAYED_BY) AS 
  select NPC_ID,NPC_RACE,NPC_NAME,NPC_PERSONALITY,NPC_SKILLS,NPC_HITPOINTS,NPC_M
ANA,NPC_ARC_MANA,NPC_CHAOS_MANA,NPC_DIVINITY,NPC_ITEMS,NPC_DRESSCODE,NPC_DESC,NP
C_SHORT_DESC,NPC_PLAYED_BY from kdr_npcs;

